# 스프링 프로필 : local (본인 로컬 컴퓨터로 톰캣 실행, H2 인메모리 DB)
spring:
  jackson:
    default-property-inclusion: non_null;
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:postgres:192.168.1.95:5432/postgres
    username: postgres
    password: 1234
  jpa:
    show-sql: true # 전송 쿼리 확인, 애플리케이션 실행과정에 쿼리의 실행 구문을 모두 보여줌
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 'update'로 변경
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용