# 스프링 프로필 : prod (AWS EC2 서버로 톰캣 실행, 운영 Postgresql DB)
spring:
  datasource:
    jackson:
      default-property-inclusion: non_null;
    h2:
      console:
        enabled: false
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    #show-sql: true # 전송 쿼리 확인, 애플리케이션 실행과정에 쿼리의 실행 구문을 모두 보여줌
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 'validate'
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용
logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-Key: ${AWS_ACCESS_KEY_ID}
      secret-Key: ${AWS_SECRET_ACCESS_KEY}