# 스프링 프로필 : local (본인 로컬 컴퓨터로 톰캣 실행, 원내 Postgresql DB)
spring:
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS address # 메모리 H2 DB 경로 설정
  jpa:
    #show-sql: true # 전송 쿼리 확인, 애플리케이션 실행과정에 쿼리의 실행 구문을 모두 보여줌
    hibernate:
      ddl-auto: create  # 매번 스키마 생성 (개발/로컬 환경에 적합)
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect  # H2 방언 사용
        use_sql_comments: true
    # defer-datasource-initialization: true  # 데이터 소스 초기화를 지연
  devtools:
    livereload:
      enabled: true # 파일(특히 정적 리소스나 템플릿)이 변경되면 livereload 서버가 브라우저에 변경을 감지하도록 신호를 보내어 자동으로 새로고침되게 함
    restart:
      enabled: false # Java 클래스 변경에 따른 애플리케이션 자동 재시작을 제어하는 옵션
  thymeleaf:
    cache: false # 템플릿을 수정할 때마다 변경 사항이 바로 반영되도록 캐싱 비활성화

logging.level:
  org.hibernate.SQL: debug
  # 하이버네이트 6 이상
  org.hibernate.orm.jdbc.bind: trace
  # 하이버네이트 5 이하
  #org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  swagger-ui:
    path: /swagger-ui
    group-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**