# 스프링 프로필 : local (본인 로컬 컴퓨터로 톰캣 실행, H2 인메모리 DB)
spring:
  jackson:
    default-property-inclusion: NON_NULL
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:postgresql://192.168.1.95:5432/postgres
    username: postgres
    password: 1234
  jpa:
    #show-sql: true # 전송 쿼리 확인, 애플리케이션 실행과정에 쿼리의 실행 구문을 모두 보여줌
    hibernate:
      ddl-auto: validate  # 개발 환경에서는 담당자 외 'validate'로 변경
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL 방언 사용
  devtools:
    livereload:
      enabled: true # 파일(특히 정적 리소스나 템플릿)이 변경되면 livereload 서버가 브라우저에 변경을 감지하도록 신호를 보내어 자동으로 새로고침되게 함
    restart:
      enabled: false # Java 클래스 변경에 따른 애플리케이션 자동 재시작을 제어하는 옵션
  thymeleaf:
    cache: false # 템플릿을 수정할 때마다 변경 사항이 바로 반영되도록 캐싱 비활성화

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui
    group-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**